### ISSUE TITLE
Suggestion Requested

### ISSUE THREAD

**Issue by lightng03** [merosss/VRepRosQuadSwarm#5]
Hello Francesco !

This is not exactly an issue with the project. I didn't know how to contact you so I am posting it here. 
I was wondering if you could point me in the right direction.
I am trying to simulate is to sync movement of multiple quadcopters models.
Something like flying in formation as shown in the following video. (https://youtu.be/AiCFtmdrvHM?t=30s).

Do you have any suggestions for me ?

Cheers

**Comment by fwanderlingh** [comment]
Sorry but I'm not actively mantaining the repository by now. Anyway to achieve what you say, if you're still dealing with the problem, maybe the easiest way is to define correctly the waypoints you want them to go in such a way they keep the same relative position. Otherwise you could define a SingleMaster/MultipleSlaves scenario where you assign different positions to be kept by each Slave quadcopter which are relative to the Master one (and give waypoints to the latter of course).

Cheers
